/*
 * This source file was generated by the Gradle 'init' task
 * ./gradlew :app:run
 */
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
